# Generated by Django 2.2.6 on 2019-11-06 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_auto_20191106_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 14, 19, 51, 632858, tzinfo=utc)),
        ),
    ]
